version: "3"
services:
  develop:
    build: .
    ports:
      - "3604:3604"
    container_name: gfw-imazon-alerts-api-develop
    environment:
      PORT: 3604
      NODE_PATH: app/src
      NODE_ENV: dev
      CARTODB_USER: wri-01
      API_GATEWAY_URL: http://mymachine:9000
      GATEWAY_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:3604
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      FASTLY_ENABLED: "false"
    command: develop
    volumes:
      - ./app:/opt/gfw-imazon-alerts-api/app
