prod:
  image: vizzuality/gfw-imazon-alerts-api:1.2.0${STAGING}
  ports:
    - "3600"
  env_file:
    - prod.env
  command: start
  dns: ${DNS_SERVER}
  restart: always
  log_driver: "syslog"
  log_opt:
    syslog-address: ${SYSLOG_ADDRESS}
    tag: gfw-imazon-alerts-api${STAGING}
