version: "3"
services:
  develop:
    build: .
    ports:
      - "3600:3600"
    container_name: gfw-imazon-alerts-api-develop
    environment:
      PORT: 3600
      NODE_PATH: app/src
      CT_REGISTER_MODE: auto
      NODE_ENV: dev
      CARTODB_USER: wri-01
      API_GATEWAY_URL: http://mymachine:9000
      CT_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:3600
      API_VERSION: v1
    command: develop
    volumes:
      - ./app:/opt/gfw-imazon-alerts-api/app
