apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: gfw
  name: imazon
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: imazon
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
